### ISSUE TITLE
Problem with nbextensions

### ISSUE THREAD

**Issue by kdeleeuw11** [jupyter/help#103]
I have the following problems with nbextensions:
When launching the Jupyter Notebook, I get a warning: 
[W 15:35:03.175 NotebookApp] server_extensions is deprecated, use nbserver_extensions

and also a warning:
[W 15:35:04.619 NotebookApp] Error loading server extension nbextensions
    Traceback (most recent call last):
      File "/Users/kees/anaconda/envs/pyk3/lib/python3.4/site-packages/notebook/notebookapp.py", line 1046, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/kees/anaconda/envs/pyk3/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/Users/kees/Library/Jupyter/extensions/nbextensions.py", line 8, in <module>
        from notebook.nbextensions import _get_nbext_dir as get_nbext_dir
    ImportError: cannot import name '_get_nbext_dir'

After launching the notebook, extensions are working with the exception of conda extensions. When clicking on the Nbextensions tab, I get the following window:
￼
![screen shot 2016-12-06 at 10 33 32 am](https://cloud.githubusercontent.com/assets/9377284/20907058/ef3e62c2-bb9f-11e6-83a5-c1fde734db51.png)

When clicking on the Conda tab, I get the following window:
![screen shot 2016-12-06 at 10 38 04 am](https://cloud.githubusercontent.com/assets/9377284/20907093/3b50dcf8-bba0-11e6-8465-177d9d56c1dc.png)

I have been searching for solutions on the web and found a few which I tried to implement. I am not very technical and have been unsuccessful. There is obviously something wrong with the configuration of the Jupyter Notebook. I am using the notebook a lot and would like it to work properly. Any help will be very much appreciated

**Comment by takluyver** [comment]
@juhasch @jcb91 @jfbercher - can you help with this extensions related question? Thanks.

**Comment by juhasch** [comment]
Is this an old version of the notebook extensions ?
You might want to update in this case (GitHub, PyPi, conda-forge).

There are some hints for troubleshooting in the docs:
http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/troubleshooting.html
(feedback is very welcome)

**Comment by kdeleeuw11** [comment]
Hi,
Thanks very much for your help and suggestions.  I think I have resolved the issues by re-installing Anaconda. I should have thought about this in the first place

**Comment by takluyver** [comment]
Thanks Kees :-)
