### ISSUE TITLE
Running python setup.py js css fails for me with the below error:

### ISSUE THREAD

**Issue by wangxiaobaidu11** [jupyter/help#114]
```python
$python setup.py js css
running js
running jsdeps
> npm install --progress=false
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm run bower

> jupyter-notebook-deps@4.0.0 bower /home/jupyterlab/paddle/notebook
> bower install --allow-root --config.interactive=false

Missing /home/jupyterlab/paddle/notebook/notebook/static/built/index.js
> npm run build:js

> jupyter-notebook-deps@4.0.0 build:js /home/jupyterlab/paddle/notebook
> webpack

Error
    at /home/jupyterlab/paddle/notebook/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/home/jupyterlab/paddle/notebook/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /home/jupyterlab/paddle/notebook/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /home/jupyterlab/paddle/notebook/node_modules/async/lib/async.js:726:13
    at /home/jupyterlab/paddle/notebook/node_modules/async/lib/async.js:52:16
    at done (/home/jupyterlab/paddle/notebook/node_modules/async/lib/async.js:241:17)
    at /home/jupyterlab/paddle/notebook/node_modules/async/lib/async.js:44:16
    at /home/jupyterlab/paddle/notebook/node_modules/async/lib/async.js:723:17
    at /home/jupyterlab/paddle/notebook/node_modules/async/lib/async.js:167:37
    at /home/jupyterlab/paddle/notebook/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/home/jupyterlab/paddle/notebook/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at innerCallback (/home/jupyterlab/paddle/notebook/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
    at loggingCallbackWrapper (/home/jupyterlab/paddle/notebook/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /home/jupyterlab/paddle/notebook/node_modules/tapable/lib/Tapable.js:134:6
    at /home/jupyterlab/paddle/notebook/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23
    at /home/jupyterlab/paddle/notebook/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at /home/jupyterlab/paddle/notebook/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (/home/jupyterlab/paddle/notebook/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /home/jupyterlab/paddle/notebook/node_modules/tapable/lib/Tapable.js:134:6
    at Resolver.<anonymous> (/home/jupyterlab/paddle/notebook/node_modules/enhanced-resolve/lib/ModuleAsDirectoryPlugin.js:30:12)
    at Storage.finished (/home/jupyterlab/paddle/notebook/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/jupyterlab/paddle/notebook/node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:111:15)
resolve module codemirror/addon/edit/matchbrackets in /home/jupyterlab/paddle/notebook/notebook/static/edit/js
  looking for modules in /home/jupyterlab/paddle/notebook
    /home/jupyterlab/paddle/notebook/codemirror doesn't exist (module as directory)
  looking for modules in /home/jupyterlab/paddle/notebook/notebook/static
    /home/jupyterlab/paddle/notebook/notebook/static/codemirror doesn't exist (module as directory)
  looking for modules in /home/jupyterlab/paddle/notebook/node_modules
    /home/jupyterlab/paddle/notebook/node_modules/codemirror doesn't exist (module as directory)

npm ERR! Linux 2.6.32_1-16-0-0_virtio
npm ERR! argv "/home/jupyterlab/node/bin/node" "/home/jupyterlab/node/bin/npm" "run" "build:js"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! jupyter-notebook-deps@4.0.0 build:js: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jupyter-notebook-deps@4.0.0 build:js script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jupyter-notebook-deps package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyter-notebook-deps
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jupyter-notebook-deps
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jupyterlab/paddle/notebook/npm-debug.log
Traceback (most recent call last):
  File "setup.py", line 199, in <module>
    main()
  File "setup.py", line 196, in main
    setup(**setup_args)
  File "/home/jupyterlab/python/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/jupyterlab/python/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/jupyterlab/python/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/jupyterlab/paddle/notebook/setupbase.py", line 451, in run
    run(['npm', 'run', 'build:js'])
  File "/home/jupyterlab/paddle/notebook/setupbase.py", line 322, in run
    return check_call(cmd, *args, **kwargs)
  File "/home/jupyterlab/python/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build:js']' returned non-zero exit status 1
```

**Comment by minrk** [comment]
What do you get for `node --version`?
