### ISSUE TITLE
Installing all of Jupyter via Anaconda distribution

### ISSUE THREAD

**Issue by rsvp** [jupyter/help#127]
I have Jupyter installed via Anaconda, and yesterday I updated as follows: 
`$ conda update jupyter`

However, the version has remained 1.0.0 for many months. There are 
other parts of Jupyter, for example, **jupyter_core**, say, version 4.1.0.

***Are there other conda commands which will install or update additional features of Jupyter?***

**Comment by Carreau** [comment]
hi @rsvp 

`jupyter` is just a meta package, it will simply pull out all the dependencies. and will likely stay at 1.0.0 for a loong time. 

If you want to update all you packages what you want to do is:

```
conda update --all
```

It will take care of updating all the dependencies and new versions.

Does that make sens ?

**Comment by rsvp** [comment]
hi @Carreau your suggested --all command brought up some specific packages 
which would be updated, so just to be focused I executed:
`conda update jupyter jupyter_client jupyter_console jupyter_core --yes`

Would this be sufficient to correctly update all necessary Jupyter dependencies, 
while covering the most important features?

Thanks very much, I appreciate your help.

**Comment by takluyver** [comment]
> $ conda update jupyter jupyter_client jupyter_console jupyter_core --yes

> Would this be sufficient to correctly update all necessary Jupyter dependencies, while covering the most important features?

I can't remember exactly how conda works with updating. Those aren't all of the Jupyter packages, but I think it might update dependencies of the packages you specify as well. Check that the `notebook` package is at 4.3.1,  and IPython at 5.1.0 (those are the current versions at present).

**Comment by rsvp** [comment]
@takluyver yes, before the Jupyter line, I have this in in my update script:
`conda update ipython ipython-notebook --yes`

Selective updating takes less time than `conda update --all` 
and sometimes unneeded packages in *--all* updates/upgrades 
may result in a **downgrade** in crucial packages. 
For example, currently the *--all* option will result in a 
downgrade from numpy 1.11.0 to 1.10.0 and hence the 
scientific packages, including a downgrade of 
pandas from 0.19.0 to 0.18.2.

#### Summary: just take what you need.

**Comment by recontemplator** [comment]
I'm not sure if there are more simple way exists but following command works for me in my environment (OSX with conda 4.3.29 )

`conda update $(conda list jupyter|tail -n+3|awk '{print $1}')`

**Comment by harrypotter0** [comment]
Unable to launch Jupyter Notebook. Here is the error in command prompt ::

`[E 18:06:07.935 NotebookApp] Uncaught exception GET /tree?token=355ef28c2c4b0d560482eadb4ada5e424706aa97f0b49dd1 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8958', method='GET', uri='/tree?token=355ef28c2c4b0d560482eadb4ada5e424706aa97f0b49dd1', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Host': 'localhost:8958', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': '_xsrf=2|2e4fb38e|dd2d1047db9aa117030755b8897e415a|1524657969; username-localhost-8888="2|1:0|10:1524657969|23:username-localhost-8888|44:NjhiMmVkZDRjM2IzNDk5ZDk2MTc2NjIxM2YwNmQ4YzA=|b4cb2c8f7055ab468f84e59e2bd3c2a18b6c79cd37a7e800da2dcca25ed61938"; username-localhost-8889="2|1:0|10:1524658586|23:username-localhost-8889|44:MWRhZjhjNGJhYWE3NDBiYThlZWRkOWE0ZjAyN2QzNGE=|67ac2fb74f815329eddd54ae11ad6c08b203efd840104620f95f09dca82efba9"; username-localhost-8890="2|1:0|10:1524658902|23:username-localhost-8890|44:MjZjZDQ4YjdhZTUxNDE0OTgwMjhiMmEwYmEzZDVkZTc=|9ea250ba6dbea9ebce087bcfb5fe76eaa36f70fad110dff5790c408b1ac6fa95"; username-localhost-8891="2|1:0|10:1524659155|23:username-localhost-8891|44:NmU5ZDEwOWFiNmE5NDZiZmI2ZWI1NDM3NDYxOTk2NTE=|276426ae02ab92ec80b525a7c220d15137dc6b1024cfb33c9a04a0d842ef6834"; username-localhost-8892="2|1:0|10:1524659381|23:username-localhost-8892|44:MzFlMjg1MDIxN2U2NDBhNjk2NzliODk2ZmZhZmZhNDU=|d56ff8ae9da1d7e492253c0f91fc61ba4c9b495b3eba4174c5c8ea9c2330bc7f"; username-localhost-8884="2|1:0|10:1524659531|23:username-localhost-8884|44:N2VmY2EwNTViMThkNDhiNTg0ZWQ2MzE0OWUyZDVjYWM=|3ed099dacc93b454be3a3630c1af2a292cea90f5f36d28009236ec2d6970cbef"; username-localhost-8980="2|1:0|10:1524659542|23:username-localhost-8980|44:ZTkyNTVkMTcyNzQ1NDYwMjlhYmUxNmM3MDU5MjVhMTQ=|8e6a8c185b9ce099a9c9819d6a89e87891db417071f29b31bdaea2f5797fc048"; username-localhost-8865="2|1:0|10:1524659726|23:username-localhost-8865|44:YThjMjY4NjU4YWY5NDk5MmI5YTk1ZTAwZTMxMmMyNmE=|703b4387df59bf47a9e5ced60651bf421a990e058103227b0d9de3632046add3"', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 2897, in wrapper
        return method(self, *args, **kwargs)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/tree/handlers.py", line 53, in get
        server_root=self.settings['server_root_dir'],
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 347, in render_template
        template = self.get_template(name)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 343, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 719, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 693, in _load_template
        template = self.loader.load(self, name, globals)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/jinja2/loaders.py", line 127, in load
        code = environment.compile(source, name, filename)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 493, in compile
        self.handle_exception(exc_info, source_hint=source)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/templates/tree.html", line 8, in template
        data-base-url="{{base_url | urlencode}}"
    TemplateAssertionError: no filter named 'urlencode'
[16453:16472:0425/180607.991377:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process.
[E 18:06:07.996 NotebookApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1036, in send_error
        self.write_error(status_code, **kwargs)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 416, in write_error
        html = self.render_template('error.html', **ns)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 348, in render_template
        return template.render(**ns)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
        return self.environment.handle_exception(exc_info, True)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/templates/page.html", line 107, in template
        data-jupyter-api-token="{{token | urlencode}}"
    TemplateAssertionError: no filter named 'urlencode'
[E 18:06:07.997 NotebookApp] {
      "Accept-Language": "en-US,en;q=0.9", 
      "Accept-Encoding": "gzip, deflate, br", 
      "Host": "localhost:8958", 
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36", 
      "Connection": "keep-alive", 
      "Cookie": "_xsrf=2|2e4fb38e|dd2d1047db9aa117030755b8897e415a|1524657969; username-localhost-8888=\"2|1:0|10:1524657969|23:username-localhost-8888|44:NjhiMmVkZDRjM2IzNDk5ZDk2MTc2NjIxM2YwNmQ4YzA=|b4cb2c8f7055ab468f84e59e2bd3c2a18b6c79cd37a7e800da2dcca25ed61938\"; username-localhost-8889=\"2|1:0|10:1524658586|23:username-localhost-8889|44:MWRhZjhjNGJhYWE3NDBiYThlZWRkOWE0ZjAyN2QzNGE=|67ac2fb74f815329eddd54ae11ad6c08b203efd840104620f95f09dca82efba9\"; username-localhost-8890=\"2|1:0|10:1524658902|23:username-localhost-8890|44:MjZjZDQ4YjdhZTUxNDE0OTgwMjhiMmEwYmEzZDVkZTc=|9ea250ba6dbea9ebce087bcfb5fe76eaa36f70fad110dff5790c408b1ac6fa95\"; username-localhost-8891=\"2|1:0|10:1524659155|23:username-localhost-8891|44:NmU5ZDEwOWFiNmE5NDZiZmI2ZWI1NDM3NDYxOTk2NTE=|276426ae02ab92ec80b525a7c220d15137dc6b1024cfb33c9a04a0d842ef6834\"; username-localhost-8892=\"2|1:0|10:1524659381|23:username-localhost-8892|44:MzFlMjg1MDIxN2U2NDBhNjk2NzliODk2ZmZhZmZhNDU=|d56ff8ae9da1d7e492253c0f91fc61ba4c9b495b3eba4174c5c8ea9c2330bc7f\"; username-localhost-8884=\"2|1:0|10:1524659531|23:username-localhost-8884|44:N2VmY2EwNTViMThkNDhiNTg0ZWQ2MzE0OWUyZDVjYWM=|3ed099dacc93b454be3a3630c1af2a292cea90f5f36d28009236ec2d6970cbef\"; username-localhost-8980=\"2|1:0|10:1524659542|23:username-localhost-8980|44:ZTkyNTVkMTcyNzQ1NDYwMjlhYmUxNmM3MDU5MjVhMTQ=|8e6a8c185b9ce099a9c9819d6a89e87891db417071f29b31bdaea2f5797fc048\"; username-localhost-8865=\"2|1:0|10:1524659726|23:username-localhost-8865|44:YThjMjY4NjU4YWY5NDk5MmI5YTk1ZTAwZTMxMmMyNmE=|703b4387df59bf47a9e5ced60651bf421a990e058103227b0d9de3632046add3\"", 
      "Upgrade-Insecure-Requests": "1"
    }
[E 18:06:07.997 NotebookApp] 500 GET /tree?token=355ef28c2c4b0d560482eadb4ada5e424706aa97f0b49dd1 (127.0.0.1) 98.62ms referer=None
Created new window in existing browser session.
^Z
[9]+  Stopped                 jupyter notebook
`
