### ISSUE TITLE
DeprecationWarning: Interpreting naive datetime as local

### ISSUE THREAD

**Issue by micklat** [jupyter/help#157]
Creating a new notebook and running this cell:

```
import warnings
warnings.simplefilter('error')
```

Makes jupyter have the following exception:

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 407, in execute_request
    ident=ident)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/session.py", line 712, in send
    to_send = self.serialize(msg, ident)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/session.py", line 619, in serialize
    self.pack(msg['metadata']),
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/session.py", line 103, in <lambda>
    ensure_ascii=False, allow_nan=False,
  File "/usr/local/lib/python2.7/dist-packages/zmq/utils/jsonapi.py", line 40, in dumps
    s = jsonmod.dumps(o, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 386, in dumps
    **kw).encode(obj)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 269, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/dist-packages/simplejson/encoder.py", line 348, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/jsonutil.py", line 90, in date_default
    obj = _ensure_tzinfo(obj)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/jsonutil.py", line 43, in _ensure_tzinfo
    stacklevel=4)
DeprecationWarning: Interpreting naive datetime as local 2017-04-06 15:02:51.777429. Please add timezone info to timestamps.
```

Alternatively, if I run ```warnings.simplefilter('default')```, I get the following text every time I execute a cell:
```
/usr/lib/python2.7/dist-packages/simplejson/encoder.py:269: DeprecationWarning: Interpreting naive datetime as local 2017-04-06 15:06:56.168859. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)
```

The default behaviour of the warnings module suppresses DeprecationWarning and other warnings since 2.7 [1], so you don't see these warnings unless you change the warning filters as shown above. However, as a developer, rather than an end user, broad suppression of python's warnings is not appropriate for me.

[1] - https://docs.python.org/2/library/warnings.html

**Comment by micklat** [comment]
Ah, I guess this is a duplicate of #2239, so should I close this and comment there?
