### ISSUE TITLE
Unable to launch Jupiter in 

### ISSUE THREAD

**Issue by sirishy3** [jupyter/help#194]
System: MacOS Sierra version 10.12.3
python 3.6.2

Installed jupyter notebook using "pip3 install jupiter" . 

Closed and opened a new terminal and tried to launch the jupyter notebook using  "jupyter notebook" command, the following error came up

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/notebook/notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/notebook/notebookapp.py", line 1120, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 49] Can't assign requested address

**Comment by minrk** [comment]
You might try using a different ip/port:

    jupyter notebook --ip=127.0.0.1 --port=10101

**Comment by sirishy3** [comment]
Wow it worked!! Thanks a lot :) 

I had no idea that I have to pull off something like this and also I can send arguments.  

Wouldn't it be helpful, if the above technique is mentioned in this [link](https://github.com/jupyter/notebook#running-in-a-local-installation). It would at least save the embarrassment to a novice user.

**Comment by RedPandae** [comment]
Hi there!

you saved me with this post! I had the same issue and I tried 

> jupyter notebook --ip=127.0.0.1 --port=10101 

and it worked for me too!!

Could I ask whether it is better to change the default ip/port that Jupyter notebook uses, and how can I do that? (is even possible?)

Many thanks!
