### ISSUE TITLE
Problem with kernel hiccup

### ISSUE THREAD

**Issue by faultdiagnosistoolbox** [jupyter/help#227]
Hi all, I have an issue I hope someone can help me with since it stops me from using the wonderful Jupiter notebooks and console.

I have recently started experiencing problems that I do not recognise from before. I am not sure what is the origin since I am a bit of a Jupiter newbie.

I run python 3.6 with Jupiter 1.0 on a MacBook Pro. I run everything in a virtual environment and pip-installed everything.

> pip show jupyter
Name: jupyter
Version: 1.0.0
Summary: Jupyter metapackage. Install all the Jupyter components in one go.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
License: BSD

> pip show ipython
Name: ipython
Version: 6.2.1
Summary: IPython: Productive Interactive Computing

I normally run a notebook with an attached console which I start using
> Jupiter console --existing

Now, my problem is this: After a short while I tend to get some kernel hiccup (I included some sample error messages from the console below). After this has started to appear, it takes a long while to evaluate any expression, even 1+1 or similar trivial statements. I also have to press enter 3-4 times to start evaluation of an expression in the console. The notebook continues to work better, although I can see some strange behaviour also there (cells taking unreasonable time to evaluate for example). I don't have to do anything special to excite the problem; it happens every time now.

My questions:
1. Anyone recognise this behaviour or is it just me?
2. Anything I can do to help debug the problem?

All the best, 
  Erik

Sample console output
================
In [21]: bar.set_label/Users/erifr93/sw/pyenv/py3.6/lib/python3.6/site-packages/jupyter_console/ptshell.py:617: UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.             
  warn('The kernel did not respond to an is_complete_request. '
In [21]: bar.set_label

In [21]: plt.Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/erifr93/sw/pyenv/py3.6/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/Users/erifr93/sw/pyenv/py3.6/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 111, in get_completions
    cursor_pos=document.cursor_position
  File "/Users/erifr93/sw/pyenv/py3.6/lib/python3.6/site-packages/jupyter_console/completer.py", line 39, in complete_request
    msg = self.client.shell_channel.get_msg(timeout=self.timeout)
  File "/Users/erifr93/sw/pyenv/py3.6/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
    raise Empty
queue.Empty

In [21]: 1+1Out[21]: <bound method Artist.set_label of <matplotlib.text.Text object at 0x10ec1fcc0>>
In [21]: 1+1
       : 
       :

**Comment by faultdiagnosistoolbox** [comment]
Maybe this wasn't the right place to post a question like this. If not, is there a better place?

Secondly, some further observations:
1. If I run my code in a regular python session; I have no problems
2. If I run my code in a jupyter console, I experience the problems.

**Comment by takluyver** [comment]
This is a fine place to ask about this.

I suspect that the key is the message `UserWarning: The kernel did not respond to an is_complete_request.` When you press enter in the console, it sends an `is_complete_request` to the kernel to decide whether to execute the code now or to prompt you for another line. If the kernel doesn't reply quickly enough, then it disables that check and instead waits for a couple of blank lines together to tell it that you've finished entering that input (that's why you have to press enter several times).

However, if everything is slowing down, that's probably just a side effect of something else.

Are your packages `jupyter_console` and `ipykernel` up to date? Do you have any custom configuration or startup files for IPython?

**Comment by faultdiagnosistoolbox** [comment]
Thanks for your reply. Everything is up to date I think (see below). I'm starting to seriously suspect my machine (late 2016 MacBook Pro with touch bar). I've had serious problems with UI-timeouts and maybe the IPython kernel is sensitive to that which makes the problem visible more often than in other places. I will try the answer by @chordogg in https://discussions.apple.com/thread/7367367?start=0&tstart=0 and see if that is the cause.

Thanks again for your reply.

% pip show jupyter_console ipykernel
Name: jupyter-console
Version: 5.2.0
Summary: Jupyter terminal console
Home-page: https://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /Users/erifr93/sw/pyenv/py3.6/lib/python3.6/site-packages
Requires: ipython, prompt-toolkit, pygments, jupyter-client, ipykernel
---
Name: ipykernel
Version: 4.6.1
Summary: IPython Kernel for Jupyter
Home-page: http://ipython.org
Author: IPython Development Team
Author-email: ipython-dev@scipy.org
License: BSD
Location: /Users/erifr93/sw/pyenv/py3.6/lib/python3.6/site-packages
Requires: ipython, traitlets, jupyter-client, tornado

**Comment by takluyver** [comment]
If there's a more general issue with your computer which is causing programs to lock up, that could cause something like this in IPython.
