### ISSUE TITLE
jupyter notebook cannot use osx backend (matplotlib)

### ISSUE THREAD

**Issue by solas** [jupyter/help#232]
jupyter notebook cannot use osx backend (matplotlib).

I have had this problem on and off over many versions of osx, and usually it was related to virtual envs.
I now use python3 venv, 
python: 3.6.1
jupyter-client (5.1.0)
MacOS: HighSierra

if I attempt to use the osx backend in a notebook (%matplotlib osx), no error is emitted, and no window or figures are opened or shown when plotting.
jupyter console fails with the message: 
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x1049bbea0>)
Traceback (most recent call last):
  File "/Users/Shared/py3.6.1/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/Users/Shared/py3.6.1/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/Shared/py3.6.1/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 265, in enter_eventloop
    self.eventloop(self)
  File "/Users/Shared/py3.6.1/lib/python3.6/site-packages/ipykernel/eventloops.py", line 277, in loop_cocoa
    show.mainloop()
AttributeError: 'function' object has no attribute 'mainloop'
Using matplotlib backend: MacOSX

switching to inline or another backend does work, but I want the interactive control in osx.

**Comment by wgzhao** [comment]
+1 
I meet the same error

- python 3.5.1
- jupyter 4.4.0
- MacOS HighSierra

**Comment by takluyver** [comment]
I think this should be fixed by https://github.com/ipython/ipykernel/pull/290 . That will be released as ipykernel 4.8.
