### ISSUE TITLE
An issue about installation jupyter

### ISSUE THREAD

**Issue by unknown867** [jupyter/help#270]
Hello
When i type pip3 install jupyter,its collecting jupyter files but then it give me an error.i send you all my types on cmd pls help me:
 Not: Since the "Running setup.py install for pluggy ... error" words are red 

C:\Users\Casper™>cd C:\Users\Casper™\AppData\Local\Programs\Python\Python36\Scripts
 
C:\Users\Casper™\AppData\Local\Programs\Python\Python36\Scripts>pip3 install jupyter
Collecting jupyter
Using cached jupyter-1.0.0-py2.py3-none-any.whl
Collecting jupyter-console (from jupyter)
Using cached jupyter_console-5.2.0-py2.py3-none-any.whl
Collecting ipywidgets (from jupyter)
Using cached ipywidgets-7.1.0-py2.py3-none-any.whl
Collecting notebook (from jupyter)
Using cached notebook-5.2.2-py2.py3-none-any.whl
Collecting ipykernel (from jupyter)
Using cached ipykernel-4.7.0-py3-none-any.whl
Collecting nbconvert (from jupyter)
Using cached nbconvert-5.3.1-py2.py3-none-any.whl
Collecting qtconsole (from jupyter)
Using cached qtconsole-4.3.1-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.0 (from jupyter-console->jupyter)
Using cached prompt_toolkit-1.0.15-py3-none-any.whl
Collecting jupyter-client (from jupyter-console->jupyter)
Using cached jupyter_client-5.2.0-py2.py3-none-any.whl
Collecting pygments (from jupyter-console->jupyter)
Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting ipython (from jupyter-console->jupyter)
Using cached ipython-6.2.1-py3-none-any.whl
Collecting traitlets>=4.3.1 (from ipywidgets->jupyter)
Using cached traitlets-4.3.2-py2.py3-none-any.whl
Collecting nbformat>=4.2.0 (from ipywidgets->jupyter)
Using cached nbformat-4.4.0-py2.py3-none-any.whl
Collecting widgetsnbextension~=3.1.0 (from ipywidgets->jupyter)
Using cached widgetsnbextension-3.1.0-py2.py3-none-any.whl
Collecting jupyter-core (from notebook->jupyter)
Using cached jupyter_core-4.4.0-py2.py3-none-any.whl
Collecting ipython-genutils (from notebook->jupyter)
Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting jinja2 (from notebook->jupyter)
Using cached Jinja2-2.10-py2.py3-none-any.whl
Collecting tornado>=4 (from notebook->jupyter)
Using cached tornado-4.5.2-cp36-cp36m-win_amd64.whl
Collecting testpath (from nbconvert->jupyter)
Using cached testpath-0.3.1-py2.py3-none-any.whl
Collecting bleach (from nbconvert->jupyter)
Using cached bleach-2.1.2-py2.py3-none-any.whl
Collecting mistune>=0.7.4 (from nbconvert->jupyter)
Using cached mistune-0.8.3-py2.py3-none-any.whl
Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter)
Using cached pandocfilters-1.4.2.tar.gz
Collecting entrypoints>=0.2.2 (from nbconvert->jupyter)
Using cached entrypoints-0.2.3-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.0->jupyter-console->jupyter)
Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Collecting six>=1.9.0 (from prompt-toolkit<2.0.0,>=1.0.0->jupyter-console->jupyter)
Using cached six-1.11.0-py2.py3-none-any.whl
Collecting pyzmq>=13 (from jupyter-client->jupyter-console->jupyter)
Using cached pyzmq-16.0.3-cp36-cp36m-win_amd64.whl
Collecting python-dateutil>=2.1 (from jupyter-client->jupyter-console->jupyter)
Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting pytest; python_version >= "3.4" or python_version == "2.7" and extra == "test" (from jupyter-client->jupyter-console->jupyter)
Using cached pytest-3.3.1-py2.py3-none-any.whl
Collecting jedi>=0.10 (from ipython->jupyter-console->jupyter)
Using cached jedi-0.11.1-py2.py3-none-any.whl
Collecting pickleshare (from ipython->jupyter-console->jupyter)
Using cached pickleshare-0.7.4-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=18.5 in c:\users\casper™\appdata\local\programs\python\python36\lib\site-packages (from ipython->jupyter-console->jupyter)
Collecting colorama; sys_platform == "win32" (from ipython->jupyter-console->jupyter)
Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting decorator (from ipython->jupyter-console->jupyter)
Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython->jupyter-console->jupyter)
Using cached simplegeneric-0.8.1.zip
Collecting jsonschema!=2.5.0,>=2.4 (from nbformat>=4.2.0->ipywidgets->jupyter)
Using cached jsonschema-2.6.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->notebook->jupyter)
Using cached MarkupSafe-1.0.tar.gz
Collecting html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre (from bleach->nbconvert->jupyter)
Using cached html5lib-1.0.1-py2.py3-none-any.whl
Collecting attrs>=17.2.0 (from pytest; python_version >= "3.4" or python_version == "2.7" and extra == "test"->jupyter-client->jupyter-console->jupyter)
Using cached attrs-17.3.0-py2.py3-none-any.whl
Collecting pluggy<0.7,>=0.5 (from pytest; python_version >= "3.4" or python_version == "2.7" and extra == "test"->jupyter-client->jupyter-console->jupyter)
Using cached pluggy-0.6.0.tar.gz
Collecting py>=1.5.0 (from pytest; python_version >= "3.4" or python_version == "2.7" and extra == "test"->jupyter-client->jupyter-console->jupyter)
Using cached py-1.5.2-py2.py3-none-any.whl
Collecting parso==0.1.1 (from jedi>=0.10->ipython->jupyter-console->jupyter)
Using cached parso-0.1.1-py2.py3-none-any.whl
Collecting webencodings (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach->nbconvert->jupyter)
Using cached webencodings-0.5.1-py2.py3-none-any.whl
Installing collected packages: wcwidth, six, prompt-toolkit, decorator, ipython-genutils, traitlets, jupyter-core, pyzmq, python-dateutil, attrs, pluggy, colorama, py, pytest, jupyter-client, tornado, parso, jedi, pickleshare, pygments, simplegeneric, ipython, ipykernel, jupyter-console, jsonschema, nbformat, testpath, webencodings, html5lib, bleach, MarkupSafe, jinja2, mistune, pandocfilters, entrypoints, nbconvert, notebook, widgetsnbextension, ipywidgets, qtconsole, jupyter
Running setup.py install for pluggy ... error
Exception:
Traceback (most recent call last):
File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 24: invalid start byte
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-packages\pip\basecommand.py", line 215, in main
status = self.run(options, args)
File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-packages\pip\commands\install.py", line 342, in run
prefix=options.prefix_path,
File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
**kwargs
File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
spinner=spinner,
File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
line = console_to_str(proc.stdout.readline())
File "c:\users\casper™\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 24: invalid start byte

**Comment by unknown867** [comment]
i solved this problem  by mailing a stuff

its happe
