### ISSUE TITLE
kernal keeps dying while converting a series into dataframe

### ISSUE THREAD

**Issue by punit2106** [jupyter/help#300]
I am loading json file from in jupyter ipython notebook. Data is loaded as a series in notebook but while i am trying to convert series into dataframe, kernal keeps restarting again and again. i have tried this multiple times with different datas as well same issue is occured. One observations is while coverting cpu usages for particular thread goes to 100% and in a while kernal restarts.
`jsonlist = []
increment = 0
filecount = 0
with jsonlines.open("test.ndjson") as counter:
    for j in counter: filecount += 1 
        
print(filecount)   

# load data into dataframe, increment lines to limit number of rows for testing
data = pd.DataFrame()
jsonlist = []
increment = 0
filecount = 0

with tqdm.tqdm(jsonlines.open("test.ndjson"),total=filecount, unit="json files") as reader:
    series = [json_normalize(j) for j in reader]

data_test = pd.concat(series)
`

**Comment by punit2106** [comment]
These are the logs scene at the jupyter notebook.

   HTTPServerRequest(protocol='http', host='jupyter.smartparity.com:8888', method='GET', uri='/api/kernels/13cc8540-d5ca-44f7-a75b-66a8f3b23a36/channels?session_id=03DD5D60455C4F2C8DB3ED7FF4FDCC0F', version='HTTP/1.1', remote_ip='217.124.187.134', headers={'Host': 'jupyter.smartparity.com:8888', 'Connection': 'Upgrade', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Upgrade': 'websocket', 'Origin': 'http://jupyter.smartparity.com:8888', 'Sec-Websocket-Version': '13', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'es-ES,es;q=0.9', 'Cookie': 'username-jupyter-smartparity-com-8888="2|1:0|10:1518425090|37:username-jupyter-smartparity-com-8888|44:NDQ3YWVhNzU1YzllNDllYjk1NjM2ZTFlZmI5Y2VjNGM=|b7e941b7e1cc0d0228f1b502c91d60113d95f3751ea438421091ee75ac957cbd"; _xsrf=2|30ed0fbb|b3435aa7ea48e4069d2543bdbbe02809|1519030016', 'Sec-Websocket-Key': '8nr9jvGL/bt8tyZikY0KaQ==', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits'})
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1467, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 4, in raise_exc_info
      File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 316, in wrapped
        ret = fn(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 418, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/opt/conda/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 250, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/opt/conda/lib/python3.6/site-packages/tornado/websocket.py", line 249, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
[E 15:03:18.587 NotebookApp] Uncaught exception GET /api/kernels/13cc8540-d5ca-44f7-a75b-66a8f3b23a36/channels?session_id=03DD5D60455C4F2C8DB3ED7FF4FDCC0F (217.124.187.134)

**Comment by minrk** [comment]
How big is the data and how much memory do you have? The most common cause of sudden kernel death while loading data is an out-of-memory error.

**Comment by punit2106** [comment]
Well its a json file of 3 gb and we have a server of 64 gig. still have 32 gb memory as free. I am able to load the data so once data is loaded in list called series, i am not able to convert it to dataframe. kernal crashes before that.

**Comment by punit2106** [comment]
[pip_list.txt](https://github.com/jupyter/help/files/1741056/pip_list.txt)
[conda_list.txt](https://github.com/jupyter/help/files/1741057/conda_list.txt)

Attaching outputs from pip list and conda list

**Comment by punit2106** [comment]
Do i have any updates on this? does kernal restart is triggered by some malicious package ?

**Comment by takluyver** [comment]
Given the size involved, I'd still be inclined to think of memory limitations. Even if the system has memory free, it's possible that there's some per-process or per-user limit.

I don't know of any specific malicious packages, and I'd expect that they'd either do something more obvious (a big 'pwned' message) or less noticeable (quietly mine bitcoin in the background). Killing your kernel in some specific situation isn't funny or profitable.
