### ISSUE TITLE
Kernel error running jupyterlab in nohup

### ISSUE THREAD

**Issue by RaphaelArkadyMeyer** [jupyter/help#305]
If I launch ```nohup jupyter lab &```, then files do not open. I get a dialogue asking what kernel the last open file used, and then hang on a loading screen. If I run ```jupyter lab``` on a live terminal window, I don't get this error.

If I open the file with the old ```\tree\path\to\file```, then I see a kernel error (Failed to start kernel: Unhanded Error), pasted below.

Is there a better alternative to have jupyterlab run in the background; is nohup the problem? Any help is appreciated.

---

Ubuntu Server, Anaconda, I just updated everything, tried uninstalling and reinstalling all jupyter packages via ```conda remove``` and ```conda install```.

```
Traceback (most recent call last):
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 148, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 239, in start_kernel
    self.write_connection_file()
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 472, in write_connection_file
    kernel_name=self.kernel_name
  File "/home/ramserver/installs/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 137, in write_connection_file
    with open(fname, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/run/user/1000/jupyter/kernel-b89c64cf-fe4d-4bdd-886f-e21feaaf925e.json'
```

**Comment by takluyver** [comment]
That error looks like your user is being logged out, so XDG_RUNTIME_DIR is being deleted. If that environment variable is set when Jupyter starts, we assume that the directory it points to will remain (i.e. you will stay logged in) while Jupyter is running.

**Comment by jonalm** [comment]
I have the same problem. Is there a workaround?

**Comment by RaphaelArkadyMeyer** [comment]
I found that cron jobs allow jupyter to be run in the background without any issues.
In particular, every 5 minutes I have cron run a script that runs jupyter if it is not already running.
