### ISSUE TITLE
ERROR:tornado.application:Exception in callback functools.partial

### ISSUE THREAD

**Issue by mcmalte** [jupyter/help#34]
The code below runs fine in jupyter console (and also older iypthon notebooks) but not in jupyter notebook. In notebook, it produces the following error if in line "fig, ax = plt.subplots(1, 1, figsize=(x, 6))" the x is >13:

```
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0xb07ebb24>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/iostream.py", line 140, in <lambda>
    self.io_loop.add_callback(lambda : self._really_send(*args, **kwargs))
  File "/usr/local/lib/python3.4/dist-packages/ipykernel/iostream.py", line 150, in _really_send
    self.socket.send_multipart(msg, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/zmq/sugar/socket.py", line 236, in send_multipart
    self.send(msg, SNDMORE|flags, copy=copy, track=track)
  File "socket.pyx", line 565, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5263)
  File "socket.pyx", line 619, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5111)
  File "message.pyx", line 183, in zmq.backend.cython.message.Frame.__cinit__ (zmq/backend/cython/message.c:1682)
OverflowError: can't convert negative value to size_t

jupyter --version 4.1.0 on Linux 3.13.0-34-generic

Here's the code, any help is much appreciated:

%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

years_m = [1556, 1558, 1569, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000]
stats_m = [1.0, 1.0, 1.0, 14.0, 20.5, 23.0, 19.5, 25.0, 32.0, 28.5, 28.5, 22.5, 29.0, 22.0, 18.0, 23.0, 43.5, 32.5, 60.5, 49.5, 57.5, 40.5, 65.0, 63.5, 72.0, 96.5, 86.5, 114.0, 118.5, 152.0, 182.0, 172.0, 219.0, 189.5, 268.5, 276.0, 272.0, 230.5, 256.0, 315.0, 277.0, 313.0, 358.5, 330.5, 302.0, 320.5, 309.5, 335.5, 377.5, 366.5, 364.0, 306.5, 407.0, 413.5, 380.5, 372.0, 439.0, 415.0, 723.5, 560.0, 506.5, 542.5, 537.0, 526.0, 669.0, 674.0, 659.5, 593.0, 592.5, 644.5, 623.0, 602.5, 890.0, 1518.0, 800.5, 690.0, 697.0, 691.0, 601.0, 568.5, 607.0, 700.0, 727.0, 716.5, 698.0, 685.0, 742.0, 762.0, 921.5, 816.5, 852.5, 836.0, 867.0, 871.5, 846.0, 851.0, 833.0, 887.0, 870.0, 828.5, 929.5, 840.0, 886.0, 914.5, 928.0, 994.5, 949.5, 1136.0, 1178.5, 1092.5, 1115.5, 1032.5, 1019.0, 933.0, 965.0, 941.5, 946.0, 1134.0, 1203.0, 1121.0, 1097.0, 1116.0, 988.0, 1105.5, 1059.0, 1191.5, 1163.0, 1374.5, 1272.0, 1410.0, 1310.0, 1140.0, 1160.5, 1217.0, 1190.5, 1197.0, 1123.0, 1168.5, 1284.0, 1239.5, 1198.0, 1195.0, 1201.0, 1225.5, 1268.0, 1263.0, 1255.0, 1303.5, 1355.5, 1257.0, 1223.5, 1336.5, 1321.5, 1266.0, 1328.5, 1274.0, 1390.5, 1452.5, 1330.0, 1271.0, 1291.0, 1298.5, 1269.0, 1354.5, 1384.0, 1264.5, 2213.5, 1720.5, 1554.5, 1540.0, 1447.0, 1302.0, 1253.5, 1359.0, 1344.0, 1315.0, 1283.0, 1319.0, 1357.5, 1333.5, 1325.5, 1245.5, 1313.5, 1351.0, 1343.0, 1436.5, 1430.0, 1334.0, 1357.0, 1355.0, 1368.0, 1330.5, 1361.0, 1411.5, 1356.0, 1378.5, 1355.0, 1297.5, 1354.0, 1346.0, 1390.0, 1402.5, 1416.0, 1436.0, 1281.5, 1346.0, 1356.5, 1278.5, 1309.5, 1403.5, 1393.0, 1381.5, 1361.0, 1402.0, 1418.5, 1351.0, 1475.0, 1495.5, 1390.0, 1293.5, 1419.0, 1390.5, 1381.0, 1396.5, 1479.0, 1562.5, 1396.0, 1462.5, 1286.5, 1422.5, 1632.5, 1477.5, 1442.5, 1646.5, 1720.5, 1508.5, 1427.5, 1481.0, 1555.0, 1452.5, 1434.0, 1397.5, 1450.0, 1477.5, 1532.5, 1506.5, 1476.0, 1448.5, 1509.5, 1590.5, 1586.5, 1628.5, 1474.5, 1492.5, 1569.0, 1476.5, 1436.0, 1476.0, 1334.0, 1414.0, 1356.0, 1424.0, 1434.0, 1454.5, 1566.5, 1590.5, 1688.5, 1507.0, 1587.0, 1679.0, 1527.5, 1667.0, 1732.0, 1663.5, 1765.5, 1734.0, 1653.5, 1722.0, 1662.5, 1815.5, 1665.0, 1721.5, 1915.0, 1911.0, 1987.5, 2017.0, 2103.5, 2094.0, 2116.0, 2106.0, 2204.0, 2681.5, 3102.0, 2287.0, 2280.0, 2647.0, 2492.0, 2490.0, 2424.0, 2330.0, 2275.0, 2331.5, 2194.5, 2281.5, 2347.5, 2243.5, 2205.0, 2139.5, 2137.5, 2222.0, 2359.0, 2283.0, 2329.0, 2271.5, 2382.0, 2299.5, 2241.0, 2216.0, 2089.0, 2242.5, 2167.0, 2207.0, 2050.5, 1557.0, 91.5, 76.5, 71.0, 73.0, 62.0, 69.5, 82.0, 63.5, 64.0, 65.0, 67.0, 53.0, 48.5, 43.0, 17.0, 21.5, 20.5, 24.5, 54.0, 32.0, 36.5, 33.0, 27.0, 27.0, 21.0, 24.0, 24.5, 17.0, 23.0, 23.5, 23.0, 27.0, 25.5, 31.0, 24.5, 25.0, 32.0, 36.5, 31.5, 18.0, 16.0, 18.5, 23.0, 23.0, 34.5, 29.0, 40.0, 30.0, 29.0, 33.0, 48.5, 36.5, 21.0, 24.0, 33.0, 23.5, 21.0, 16.0, 20.0, 13.0, 21.0, 10.0, 15.0, 6.0, 3.0, 5.0, 3.0, 5.0, 9.0, 7.5, 5.0, 7.0, 4.0, 4.0, 6.0, 7.0, 4.0, 5.0, 1.0, 5.0, 4.0, 11.5, 8.0, 3.0, 6.0, 5.0, 6.0, 6.0, 2.0, 2.0, 5.0, 2.0, 5.0, 1.0, 5.0, 5.0, 2.0, 3.0, 1.0]

years_t = [1539, 1568, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000]
stats_t = [1, 1, 4, 6, 1, 3, 20, 11, 18, 15, 13, 15, 7, 17, 12, 21, 23, 22, 25, 29, 39, 48, 45, 95, 118, 232, 243, 225, 219, 320, 271, 716, 342, 489, 582, 678, 969, 605, 587, 631, 678, 828, 768, 754, 687, 725, 716, 772, 743, 720, 747, 943, 797, 833, 789, 800, 826, 827, 884, 965, 1110, 1118, 1161, 1282, 1385, 1276, 1308, 1349, 1352, 1378, 1017, 1161, 1275, 1387, 1655, 1974, 1815, 1747, 1717, 1712, 1687, 1677, 1688, 1518, 1679, 1701, 1609, 1821, 1717, 1775, 1888, 2377, 1967, 1953, 1918, 2290, 2344, 2247, 2412, 2509, 2292, 2930, 2609, 2668, 2623, 2634, 2643, 2823, 2876, 2818, 2903, 3379, 2899, 2964, 2751, 2656, 2803, 2940, 2995, 3017, 2987, 3209, 2916, 2955, 2959, 2939, 3054, 3033, 3280, 3249, 3224, 3283, 3084, 3194, 3120, 3088, 3154, 3168, 3225, 3166, 3160, 3147, 3116, 3270, 3391, 3404, 3316, 3349, 3174, 3413, 3438, 3428, 3412, 3442, 3428, 3627, 3564, 3615, 3539, 3498, 3508, 3301, 3231, 3334, 3113, 3541, 3505, 3470, 3538, 3596, 3572, 3519, 3504, 3570, 3538, 3601, 3595, 3526, 3442, 3505, 3400, 3637, 3376, 3315, 3393, 3455, 3536, 4247, 3308, 3334, 3552, 3483, 3356, 3149, 3454, 3639, 3657, 3475, 3557, 3472, 3749, 3676, 3556, 3778, 3525, 3686, 3760, 3607, 3555, 3431, 3563, 3570, 3426, 3593, 3515, 3484, 3613, 3683, 3628, 3617, 3784, 3706, 3745, 4082, 4093, 4067, 4222, 3933, 4208, 4517, 4374, 4480, 4665, 4669, 4397, 4656, 4498, 4566, 4763, 4219, 4625, 4485, 4591, 4720, 4596, 4721, 4593, 4420, 4281, 4276, 4258, 4286, 4408, 4456, 4346, 4440, 4499, 4436, 4631, 4609, 4739, 4648, 4478, 4679, 4562, 4539, 4560, 4767, 4698, 4604, 5028, 5185, 4811, 4836, 4752, 4740, 4645, 4969, 5114, 5027, 5118, 5628, 5474, 5883, 6108, 6317, 6225, 6512, 6531, 7011, 6503, 8101, 6126, 6346, 6715, 6450, 6665, 6772, 7058, 6625, 6984, 7250, 7550, 7251, 6878, 7356, 7208, 6850, 7083, 6754, 6750, 7756, 6564, 6504, 6438, 6604, 6213, 6494, 6186, 5594, 6587, 5182, 5108, 5360, 4932, 4967, 5460, 5361, 5713, 5654, 4890, 4867, 4571, 4601, 4302, 4285, 3208, 2795, 2753, 2576, 3184, 3407, 2969, 2578, 2418, 2507, 2675, 2249, 2001, 2009, 2048, 2178, 1790, 1867, 1890, 1867, 1643, 1691, 1652, 1696, 1651, 1450, 1594, 1373, 1839, 1856, 1590, 2090, 1817, 1729, 860, 555, 522, 482, 475, 413, 407, 419, 376, 428, 385, 384, 396, 396, 401, 407, 391, 357, 332, 310, 284, 273, 207, 173, 138, 123, 131, 118, 130, 112, 133, 127, 144, 137, 137, 117, 107, 116, 108, 135, 165, 130, 115, 143, 122, 120, 105, 130, 121, 103, 140, 48]

years_s = [1508, 1582, 1583, 1584, 1592, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000]
stats_s = [1, 1, 1, 1, 1, 5, 11, 6, 8, 3, 28, 14, 11, 13, 38, 41, 24, 79, 143, 120, 161, 216, 191, 101, 107, 155, 131, 117, 522, 929, 596, 190, 202, 156, 220, 137, 185, 257, 299, 204, 202, 213, 171, 227, 243, 623, 202, 257, 228, 242, 188, 664, 231, 273, 260, 267, 260, 311, 374, 1110, 1369, 794, 399, 364, 385, 408, 447, 432, 497, 482, 515, 983, 564, 849, 723, 750, 803, 721, 728, 590, 756, 1012, 670, 686, 735, 783, 898, 1143, 877, 852, 800, 941, 885, 849, 889, 1134, 950, 988, 915, 1016, 989, 1266, 1050, 1110, 1161, 1246, 1402, 1001, 951, 944, 1096, 1295, 1010, 1012, 1422, 1285, 1120, 1171, 1136, 1208, 1315, 1198, 1330, 1477, 1296, 1397, 1386, 1338, 1335, 1223, 1366, 1855, 1385, 1453, 1314, 1468, 1490, 1412, 1467, 1563, 1695, 1962, 1582, 1743, 1616, 1531, 1634, 1798, 1762, 1730, 1673, 2625, 2101, 2991, 2736, 1666, 1698, 1731, 1699, 1547, 1564, 1773, 1750, 1786, 1703, 1676, 1847, 1770, 1746, 1885, 2083, 1756, 1737, 1998, 1972, 1960, 1920, 2011, 2020, 2034, 1996, 2062, 2264, 2827, 2142, 2058, 2092, 1994, 2107, 1986, 1990, 2040, 2140, 2169, 2279, 2231, 2257, 2168, 2100, 2149, 2408, 2260, 2310, 2346, 2408, 2325, 2396, 2474, 2508, 2511, 2573, 2960, 2571, 2435, 2552, 2484, 2732, 3006, 2765, 2482, 2697, 2848, 2399, 2609, 2523, 2518, 2491, 2653, 2644, 2421, 2459, 2464, 2498, 2529, 2582, 2513, 2537, 2721, 2683, 2725, 2854, 2735, 2639, 2820, 2785, 2845, 2618, 2719, 3098, 2790, 2682, 2771, 2922, 2700, 2782, 2743, 3270, 2788, 3087, 3048, 2831, 3303, 2838, 2887, 2763, 2809, 3160, 3119, 3174, 3229, 3339, 3372, 3281, 3304, 4799, 3773, 3985, 3888, 3806, 3847, 3684, 4611, 3850, 3605, 3468, 3801, 3781, 3849, 3781, 3916, 4023, 4717, 4156, 4167, 3943, 4233, 4430, 4306, 4523, 4533, 4281, 5206, 4430, 4494, 4297, 4191, 4066, 3889, 4098, 3904, 4257, 4657, 4104, 4096, 3856, 3621, 3850, 3501, 3566, 4119, 3683, 3470, 3506, 3694, 3325, 3204, 2988, 2893, 2689, 2831, 2380, 2255, 2218, 2195, 2147, 2104, 1782, 1755, 1709, 1654, 1465, 1247, 1258, 1193, 1034, 1079, 1054, 970, 992, 974, 885, 861, 880, 897, 899, 980, 1096, 795, 716, 560, 569, 544, 536, 478, 488, 403, 380, 402, 381, 352, 406, 275, 242, 208, 246, 176, 131, 127, 142, 139, 128, 131, 112, 84, 99, 96, 87, 92, 98, 100, 75, 66, 108, 83, 92, 83, 63, 78, 72, 54, 34, 51, 42, 27, 16, 20, 15, 16, 18, 12, 15, 2]

fig, ax = plt.subplots(1, 1, figsize=(15, 6))
ax.spines['top'].set_visible(False)
ax.spines['bottom'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_visible(False)
ax.get_xaxis().tick_bottom()
ax.get_yaxis().tick_left()

plt.xticks(range(1500, 2000, 25))
plt.title('Gesamtzahl der Eintraege')

# Plot data
plt.plot(years_m, stats_m, 'b')
plt.plot(years_t, stats_t, 'g')
plt.plot(years_s, stats_s, 'r') 
```

**Comment by minrk** [comment]
What's your pyzmq version (`zmq.__version__`)?

**Comment by mcmalte** [comment]
import zmq
print(zmq.__version__)

14.0.1

**Comment by mcmalte** [comment]
import zmq
print(zmq.version)

14.0.1

**Comment by mcmalte** [comment]
I upgraded zmq to 15.2.0 and the error is gone. Thanks!
