### ISSUE TITLE
OSError: [Errno 18] Invalid cross-device link

### ISSUE THREAD

**Issue by moskiGithub** [jupyter/help#365]
Hi, jupyter team
I install jupyter on my docker
when I delete a file which in mount dir  on web UI, it return a error:
Traceback (most recent call last): File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute result = yield result File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run value = future.result() File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper yielded = next(result) File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 235, in delete yield gen.maybe_future(cm.delete(path)) File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 278, in delete self.delete_file(path) File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 499, in delete_file send2trash(os_path) File "/opt/conda/lib/python3.6/site-packages/send2trash/plat_other.py", line 192, in send2trash trash_move(path_b, dest_trash, topdir) File "/opt/conda/lib/python3.6/site-packages/send2trash/plat_other.py", line 103, in trash_move os.rename(src, op.join(filespath, destname)) OSError: [Errno 18] Invalid cross-device link: b'/home/jovyan/Dataset/project1/Untitled Folder' -> b'/home/jovyan/.local/share/Trash/files/Untitled Folder'

**Comment by takluyver** [comment]
Could you try this code and share the results:

```python
import os
p = os.path.realpath(b'/home/jovyan/Dataset/project1/Untitled Folder')
while True:
    print(p, os.stat(p).st_dev)
    parent = os.path.dirname(p)
    if parent == p:
        break
    p = parent
```

This prints what device (i.e. filesystem) the file and each of its parent directories are on.
