### ISSUE TITLE
dead python2 kernel

### ISSUE THREAD

**Issue by mhuang6776** [jupyter/help#412]
I had success before, but today it gives me this error. New to jupyter and python, could anyone help please? Thank you!!!

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\python27\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "c:\python27\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "c:\python27\lib\site-packages\ipykernel\connect.py", line 14, in <module>
    from IPython.paths import get_ipython_dir
  File "c:\python27\lib\site-packages\IPython\paths.py", line 10, in <module>
    from IPython.utils.path import (
ImportError: cannot import name ensure_dir_exists

**Comment by minrk** [comment]
This suggests that IPython is too old:

    C:\python27\Python -m pip install --upgrade ipython
