### ISSUE TITLE
jupyter notebook error

### ISSUE THREAD

**Issue by pearsongong** [jupyter/help#454]
Traceback (most recent call last):
  File "/Users/gongjianchao/anaconda3/envs/tensorflow/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/Users/gongjianchao/anaconda3/envs/tensorflow/lib/python2.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/gongjianchao/anaconda3/envs/tensorflow/lib/python2.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/gongjianchao/anaconda3/envs/tensorflow/lib/python2.7/site-packages/traitlets/config/application.py", line 89, in catch_config_error
    app.print_help()
  File "/Users/gongjianchao/anaconda3/envs/tensorflow/lib/python2.7/site-packages/traitlets/config/application.py", line 385, in print_help
    self.print_subcommands()
  File "/Users/gongjianchao/anaconda3/envs/tensorflow/lib/python2.7/site-packages/traitlets/config/application.py", line 377, in print_subcommands
    print(os.linesep.join(lines))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 4: ordinal not in range(128)

**Comment by minrk** [comment]
What do you get from `locale`? I would also highly recommend using Python 3 if you can, which resolves most unicode issues encountered in Python 2.
