### ISSUE TITLE
Can't download as anything in jupyter notebook

### ISSUE THREAD

**Issue by kkew3** [jupyter/help#467]
When I use "download as" and select anything in browser, it pops up "500 Internal Server Error". If I instead go to terminal and type

```bash
jupyter nbconvert --to ${anything} filename.ipynb
```

where `${anything}` is substituted with any supported format (e.g.: `pdf`, `html`, `latex`), it complains: "ValueError: Unknown exporter "`${anything}`", did you mean one of: ?". Full traceback below:

```plain
Traceback (most recent call last):
  File "$VIRTUAL_ENV/bin/jupyter-nbconvert", line 12, in <module>
    sys.exit(main())
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 337, in start
    self.convert_notebooks()
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 496, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/nbconvert/exporters/base.py", line 113, in get_exporter
    % (name, ', '.join(get_export_names())))
ValueError: Unknown exporter "${anything}", did you mean one of: ?
```

where `$VIRTUAL_ENV` is the home directory of the `virtualenv` environment.

Version info:

```plain
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
ipython==6.4.0
prompt-toolkit==1.0.15
```

I take these package versions from [a post under this issue](https://github.com/jupyter/jupyter_console/issues/158#issue-330642313), in order to solve malfunction of ipython console where multi-line function cannot be defined (broken dependency with `prompt-toolkit`).

Thanks for any suggestion to fix the "download as" issue.

**Comment by minrk** [comment]
Can you include the complete output of `pip list`? How did you install nbconvert? I suspect this points to a problem installing and/or reading the entrypoints metadata used to find exporters.

**Comment by kkew3** [comment]
Thanks for your response. I believe `nbconvert` is installed automatically as one of the dependencies of `jupyter`. In fact, I think I've located the problem. I posted my solution under Issues of `ipython`. In case I should have posted it here, this is the link: https://github.com/ipython/ipython/issues/11512.
