### ISSUE TITLE
When opening jupyter notebook, error: 500 Internal Server Error

### ISSUE THREAD

**Issue by elaine-peiru** [jupyter/help#539]
I got this error when I opened jupyter notebook, I already tried several commend line and it didn't work in my case. Can someone help me to check what happened? Thank you

```
[E 01:28:26.248 NotebookApp] Uncaught exception GET /notebooks/Downloads/Computational-Text-Analysis-2018-19-master/Complete-Code/Exercise-Week5.ipynb (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/notebooks/Downloads/Computational-Text-Analysis-2018-19-master/Complete-Code/Exercise-Week5.ipynb', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 3174, in wrapper
        return method(self, *args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/notebook/notebook/handlers.py", line 59, in get
        get_custom_frontend_exporters=get_custom_frontend_exporters
      File "/anaconda3/lib/python3.6/site-packages/notebook/base/handlers.py", line 519, in render_template
        return template.render(**ns)
      File "/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
        return original_render(self, *args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/anaconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "/anaconda3/lib/python3.6/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/anaconda3/lib/python3.6/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/anaconda3/lib/python3.6/site-packages/notebook/templates/notebook.html", line 120, in block "header"
        {% for exporter in get_custom_frontend_exporters() %}
      File "/anaconda3/lib/python3.6/site-packages/notebook/notebook/handlers.py", line 19, in get_custom_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/anaconda3/lib/python3.6/site-packages/nbconvert/__init__.py", line 7, in <module>
        from . import postprocessors
      File "/anaconda3/lib/python3.6/site-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
        from .serve import ServePostProcessor
      File "/anaconda3/lib/python3.6/site-packages/nbconvert/postprocessors/serve.py", line 19, in <module>
        class ProxyHandler(web.RequestHandler):
      File "/anaconda3/lib/python3.6/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
        @web.asynchronous
    AttributeError: module 'tornado.web' has no attribute 'asynchronous'
[E 01:28:26.256 NotebookApp] {
      "Host": "127.0.0.1:8888",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "Referer": "http://127.0.0.1:8888/tree/Downloads/Computational-Text-Analysis-2018-19-master/Complete-Code",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7",
      "Cookie": "_xsrf=2|5abca803|28f9dbe081bb042813fde087b45c0d7c|1550575891; username-127-0-0-1-8890=\"2|1:0|10:1552348438|23:username-127-0-0-1-8890|44:NzY0MjNjMTJlZDgyNDE5OGEwMGNhOTIxOGQyYTcxNzc=|6262fb7af624bf1398f1f39ad58116df0c1b18018cff38c17c45092e7dc381a4\"; username-127-0-0-1-8889=\"2|1:0|10:1552349591|23:username-127-0-0-1-8889|44:MGZjOWQ3OGVkNTRmNGJhZjllNzQ3MWUwMTQ0Yjk0OTU=|b1740e5eb1b32edbb1cf7c0a45c9862d00f970e973c48b5b53199da680a77392\"; username-127-0-0-1-8888=\"2|1:0|10:1552350490|23:username-127-0-0-1-8888|44:MTgxYjNmYmM5YmU0NDRkMGIxOWY3NTQxYmQwZDNmMDU=|a4003ffa912cd68368e4f412cccb9f73eea55c0bc027060c8911a74489c55a9a\""
    }
[E 01:28:26.256 NotebookApp] 500 GET /notebooks/Downloads/Computational-Text-Analysis-2018-19-master/Complete-Code/Exercise-Week5.ipynb (127.0.0.1) 127.13ms referer=http://127.0.0.1:8888/tree/Downloads/Computational-Text-Analysis-2018-19-master/Complete-Code


```

**Comment by elaine-peiru** [comment]
I solved this myself by downgrade it to 5.4.0.. don't know why this would happened
