### ISSUE TITLE
nb convert throws ImportError: No module named IPython.lib.lexers when run on terminal

### ISSUE THREAD

**Issue by hassanshaikley** [jupyter/help#58]
> jupyter nbconvert test.ipynb
> 
> ImportError: No module named IPython.lib.lexers

I am not sure why this is happening ):

**Comment by Carreau** [comment]
Can you give the full stacktrace ? It seem like you did not install nbconvert correctly, how did you installed ?

**Comment by hassanshaikley** [comment]
```
jupyter nbconvert --to html test.ipynb
[NbConvertApp] Converting notebook test.ipynb to html
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Library/Python/2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Library/Python/2.7/site-packages/nbconvert/nbconvertapp.py", line 293, in start
    self.convert_notebooks()
  File "/Library/Python/2.7/site-packages/nbconvert/nbconvertapp.py", line 457, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/Library/Python/2.7/site-packages/nbconvert/nbconvertapp.py", line 428, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/Library/Python/2.7/site-packages/nbconvert/nbconvertapp.py", line 357, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/exporter.py", line 165, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/exporter.py", line 183, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/html.py", line 65, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/templateexporter.py", line 203, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/../templates/html/full.tpl", line 2, in top-level template code
    {% from 'mathjax.tpl' import mathjax %}
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/../templates/html/basic.tpl", line 1, in top-level template code
    {%- extends 'display_priority.tpl' -%}
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/../templates/skeleton/display_priority.tpl", line 1, in top-level template code
    {%- extends 'null.tpl' -%}
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 26, in top-level template code
    {%- block body -%}
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/../templates/html/full.tpl", line 63, in block "body"
    {{ super() }}
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 28, in block "body"
    {%- block any_cell scoped -%}
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 30, in block "any_cell"
    {%- block codecell scoped -%}
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/../templates/html/basic.tpl", line 6, in block "codecell"
    {{ super() }}
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 31, in block "codecell"
    {%- block input_group -%}
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/../templates/html/basic.tpl", line 12, in block "input_group"
    {{ super() }}
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/../templates/skeleton/null.tpl", line 33, in block "input_group"
    {%- block input -%}{%- endblock input -%}
  File "/Library/Python/2.7/site-packages/nbconvert/exporters/../templates/html/basic.tpl", line 49, in block "input"
    {{ cell.source | highlight_code(metadata=cell.metadata) }}
  File "/Library/Python/2.7/site-packages/nbconvert/filters/highlight.py", line 54, in __call__
    language, metadata)
  File "/Library/Python/2.7/site-packages/nbconvert/filters/highlight.py", line 122, in _pygments_highlight
    from IPython.lib.lexers import IPythonLexer
ImportError: No module named IPython.lib.lexers

```



I installed with

`pip install nbconvert`

it says 

`Requirement already satisfied (use --upgrade to upgrade):
`

So I imagine it is installed correctly : (

**Comment by takluyver** [comment]
Is IPython installed in the same environment? try a `pip install ipython` to make sure.

**Comment by hassanshaikley** [comment]
pip install ipython

throws an error ):

```
pip install ipython
Collecting ipython
  Using cached ipython-4.2.0-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): traitlets in /Library/Python/2.7/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): gnureadline; sys_platform == "darwin" and platform_python_implementation == "CPython" in /Library/Python/2.7/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): pexpect; sys_platform != "win32" in /Library/Python/2.7/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): simplegeneric>0.8 in /Library/Python/2.7/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): backports.shutil-get-terminal-size in /Library/Python/2.7/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): decorator in /Library/Python/2.7/site-packages (from ipython)
Collecting setuptools>=18.5 (from ipython)
  Using cached setuptools-23.1.0-py2.py3-none-any.whl
Collecting pickleshare (from ipython)
  Using cached pickleshare-0.7.2-py2.py3-none-any.whl
Collecting appnope; sys_platform == "darwin" (from ipython)
  Using cached appnope-0.1.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /Library/Python/2.7/site-packages (from traitlets->ipython)
Requirement already satisfied (use --upgrade to upgrade): ptyprocess>=0.5 in /Library/Python/2.7/site-packages (from pexpect; sys_platform != "win32"->ipython)
Collecting pathlib2; python_version in "2.6 2.7 3.2 3.3" (from pickleshare->ipython)
  Using cached pathlib2-2.1.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pathlib2; python_version in "2.6 2.7 3.2 3.3"->pickleshare->ipython)
Installing collected packages: setuptools, pathlib2, pickleshare, appnope, ipython
  Found existing installation: setuptools 1.1.6
    Uninstalling setuptools-1.1.6:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
    copytree(src, real_dst, symlinks=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
**Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', '/var/folders/wc/38n1pfj55p3bfgsw_rzbcs2h0000gn/T/pip-ofiBq6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py', "[Errno 1] Operation not permitted: '/var/folders/wc/38n1pfj55p3bfgsw_rzbcs2h0000gn/T/pip-ofiBq6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', '/var/folders/wc/38n1pfj55p3bfgsw_rzbcs2h0000gn/T/pip-ofiBq6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc', "[Errno 1] Operation not permitted: '/var/folders/wc/38n1pfj55p3bfgsw_rzbcs2h0000gn/T/pip-ofiBq6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/__init__.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', '/var/folders/wc/38n1pfj55p3bfgsw_rzbcs2h0000gn/T/pip-ofiBq6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py', "[Errno 1] Operation not permitted: '/var/folders/wc/38n1pfj55p3bfgsw_rzbcs2h0000gn/T/pip-ofiBq6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.py'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', '/var/folders/wc/38n1pfj55p3bfgsw_rzbcs2h0000gn/T/pip-ofiBq6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc', "[Errno 1] Operation not permitted: '/var/folders/wc/38n1pfj55p3bfgsw_rzbcs2h0000gn/T/pip-ofiBq6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib/markers.pyc'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', '/var/folders/wc/38n1pfj55p3bfgsw_rzbcs2h0000gn/T/pip-ofiBq6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib', "[Errno 1] Operation not permitted: '/var/folders/wc/38n1pfj55p3bfgsw_rzbcs2h0000gn/T/pip-ofiBq6-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/_markerlib'")]**
```

**Comment by takluyver** [comment]
setuptools 1.1.6? That's pretty old. Maybe you need to manually update setuptools before you can do anything else... I'm not really sure. You could always just create an environment with conda or venv and do what you need to in there.

**Comment by hassanshaikley** [comment]
Okay! Conda worked. Thank you : )

**Comment by takluyver** [comment]
Great. I suspect the old version of setuptools was the culprit here.
