### ISSUE TITLE
pysqlite2 error

### ISSUE THREAD

**Issue by jjough** [jupyter/help#64]
I've just installed a fresh version of Jupyter and python 2.7 using brew, but I'm having trouble getting it to run.

I first got the following error:

```
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python2.7/site-packages/notebook/notebookapp.py", line 62, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 12, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ImportError: No module named pysqlite2
```

So I installed pysqlite with pip (I thought this was bundled with python anyway), and now I get a different error:

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python2.7/site-packages/notebook/notebookapp.py", line 62, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 12, in <module>
    from pysqlite2 import dbapi2 as sqlite3
  File "/usr/local/lib/python2.7/site-packages/pysqlite2/dbapi2.py", line 28, in <module>
    from pysqlite2._sqlite import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/pysqlite2/_sqlite.so, 2): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: /usr/local/lib/python2.7/site-packages/pysqlite2/_sqlite.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/pysqlite2/_sqlite.so`
```

What should I do now?

Here are the results of `pip freeze`, in case that is useful:

```
appnope==0.1.0
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
BeautifulSoup==3.2.1
certifi==2016.2.28
configparser==3.5.0
decorator==4.0.10
Django==1.9.7
entrypoints==0.2.2
funcsigs==1.0.2
functools32==3.2.3.post2
ipykernel==4.3.1
ipython==5.0.0
ipython-genutils==0.1.0
ipywidgets==5.1.5
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.3.0
jupyter-console==5.0.0
jupyter-core==4.1.0
MarkupSafe==0.23
mistune==0.7.3
mock==2.0.0
nbconvert==4.2.0
nbformat==4.0.1
nose==1.3.7
notebook==4.2.1
numpy==1.11.1
pathlib2==2.1.0
pbr==1.10.0
pexpect==4.2.0
pickleshare==0.7.2
Pillow==3.3.0
prompt-toolkit==1.0.3
ptyprocess==0.5.1
Pygments==2.1.3
pysqlite==2.8.2
pyzmq==15.3.0
qtconsole==4.2.1
requests==2.10.0
scipy==0.17.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
stevedore==1.16.0
terminado==0.6
testpath==0.3
tornado==4.3
traitlets==4.2.2
virtualenv==15.0.2
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.1
wcwidth==0.1.7
widgetsnbextension==1.2.3
```

And in general, I seem to be spending 90% of my time troubleshooting this kind of stuff rather than actually working on the things I want to. I assume this is not the normal case! Where can I learn the information needed to navigate these kinds of errors? Thanks.

**Comment by takluyver** [comment]
sqlite is normally bundled with Python, but it's possible to compile Python without it, and that's when we look for the external pysqlite2. I suspect we caught a similar exception from loading `sqlite3` and tried the fallback. I'm not sure what would cause that error, but maybe you have a different version of sqlite to the one Python and pysqlite were compiled with.

**Comment by jjough** [comment]
Thanks. So what should I try?

**Comment by takluyver** [comment]
Reinstall sqlite with Homebrew? This is a total guess, though. I'm hoping someone who knows more about Mac stuff will come and help you.

**Comment by jjough** [comment]
Thanks. Uninstalled everything, updated everything and reinstalled. All
working now!

**Comment by takluyver** [comment]
OK, glad it's working.

**Comment by choopage** [comment]
After reinstalling sqlite, mine worked too. Thanks for the recommendation.
