### ISSUE TITLE
The kernel has died, and the automatic restart has failed. 

### ISSUE THREAD

**Issue by lwilhoit** [jupyter/help#97]
I have just started using Jupyter, running OS 10.12.1.  When I start an iPython kernel, it starts but after a few seconds I get the message "The kernel has died, and the automatic restart has failed. "  I have tried to restart the kernel, and tried restarting my computer, and tried it on different days, but I always have this problem.

**Comment by takluyver** [comment]
Are there any error messages in the terminal where you started the notebook? That sometimes has more info when kernels are dying.

**Comment by lwilhoit** [comment]
Hi,

Actually, it is working now.  But as I mentioned it worked previously, then stopped working. Here are the messages from the terminal:

[I 09:07:16.506 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 09:07:17.056 NotebookApp] [nb_anacondacloud] enabled
[I 09:07:17.059 NotebookApp] [nb_conda] enabled
[I 09:07:17.126 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 09:07:17.126 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 09:07:17.130 NotebookApp] Serving notebooks from local directory: /Users/larrywilhoit/Dropbox/Python/math
[I 09:07:17.130 NotebookApp] 0 active kernels 
[I 09:07:17.130 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 09:07:17.130 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 09:07:32.418 NotebookApp] Kernel started: 4a564972-0884-4f0c-83ab-df1c96273511
Traceback (most recent call last):
  File "/Users/larrywilhoit/anaconda/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/larrywilhoit/anaconda/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/larrywilhoit/anaconda/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/larrywilhoit/anaconda/lib/python3.5/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/larrywilhoit/anaconda/lib/python3.5/site-packages/ipykernel/connect.py", line 10, in <module>
    from subprocess import Popen, PIPE
  File "/Users/larrywilhoit/anaconda/lib/python3.5/subprocess.py", line 439, in <module>
    import selectors
  File "/Users/larrywilhoit/anaconda/lib/python3.5/selectors.py", line 10, in <module>
    import math
  File "/Users/larrywilhoit/Dropbox/Python/math/math.py", line 55
    series_n = print_series(int(n))
                                  ^
IndentationError: unindent does not match any outer indentation level
[I 09:07:35.423 NotebookApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/Users/larrywilhoit/anaconda/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/larrywilhoit/anaconda/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/larrywilhoit/anaconda/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/larrywilhoit/anaconda/lib/python3.5/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/larrywilhoit/anaconda/lib/python3.5/site-packages/ipykernel/connect.py", line 10, in <module>
    from subprocess import Popen, PIPE
  File "/Users/larrywilhoit/anaconda/lib/python3.5/subprocess.py", line 439, in <module>
    import selectors
  File "/Users/larrywilhoit/anaconda/lib/python3.5/selectors.py", line 10, in <module>
    import math
  File "/Users/larrywilhoit/Dropbox/Python/math/math.py", line 55
    series_n = print_series(int(n))
                                  ^
IndentationError: unindent does not match any outer indentation level


Larry

**Comment by takluyver** [comment]
Aha, you've got a file called `math.py` in the working directory where the kernel runs. That's clashing with the standard library [math module](https://docs.python.org/3/library/math.html). So when it tries to `import math`, it's finding your file instead. You'll need to call that file something else. This is a standing annoyance with Python.

**Comment by lwilhoit** [comment]
Thanks for that information.  A good thing to know!

Larry

**Comment by Bitewulign** [comment]
when I run a code in anaconda jupyter, i got an error
''The kernel has died, and the automatic restart has failed.''
I upgrade all the libraries. However, the error still exists. I couldn't go to the next step. Any help is appreciated!
